language: rust

os:
  - linux
  - osx

rust:
  - stable

cache:
  directories:
    - $HOME/.cargo

script:
  - rustup component add rustfmt
  - cargo fmt --all -- --check
  - cargo build --all
  - cargo test
  - cargo test --no-default-features
  - cargo doc --all --no-deps
